CREATE OR REPLACE PROCEDURE STP_LIST_SOLICITUD_DETALLE(
Val_COD_LINEA_NEGOCIO IN CHAR,
Val_COD_MODAL_EST IN CHAR,
Val_COD_PERIODO IN CHAR,
Val_COD_TRAMITE IN NUMBER,
Val_ESTADO IN VARCHAR2,
ObjResponse OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN ObjResponse FOR
  SELECT s.COD_LINEA_NEGOCIO,
         s.COD_MODAL_EST,
         s.COD_PERIODO,
         s.COD_PERIODO,
         s.COD_TRAMITE,
         s.COD_UNICO,
         s.ESTADO,
         s.COD_ALUMNO,
         d.COD_DETALLE,
         d.COD_CURSO,
         d.COD_TIPO_PRUEBA,
         d.NUM_PRUEBA,
         d.SECCION,
         d.GRUPO,
         d.ESTADO_CURSO
  FROM SOLICITUD s JOIN DETALLE_SOLICITUD d ON s.COD_UNICO = d.COD_UNICO
  WHERE (Val_COD_LINEA_NEGOCIO IS NULL OR  s.COD_LINEA_NEGOCIO = Val_COD_LINEA_NEGOCIO) AND
       (Val_COD_MODAL_EST IS NULL OR  s.COD_MODAL_EST = Val_COD_MODAL_EST) AND
       (Val_COD_PERIODO IS NULL OR  s.COD_PERIODO = Val_COD_PERIODO) AND
       (Val_COD_TRAMITE = 0  OR  s.COD_TRAMITE = Val_COD_TRAMITE) AND
       (Val_ESTADO IS NULL OR  s.ESTADO = Val_ESTADO);
END;
